name: branchDeploy

on:
  push:
    branches: [ "main" ]
    paths:
      -  'force-app/**'  
  workflow_dispatch:

jobs:
  branch-deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'save secret to file'
        run: | 
          echo $secureKey > secure.key
        env:
          secureKey: ${{ secrets.secureKey }}

      - name: 'sfdx auth'
        run: |
          sfdx force:auth:jwt:grant --loglevel ${{ env.logLevel }} --username ${{ env.userName }} --jwt-key-file ${{secure.key}} --client-id ${{ secret.consumerKey }} --instance-url ${{ env.instanceURL }} --alias ${{ env.orgAlias }}

      - name: 'branch deploy'
        run: |
          sfdx force:source:deploy --loglevel ${{ env.logLevel }} --targetusername ${{ env.orgAlias }} --testlevel ${{ env.testLevel }} --sourcepath ${{ env.sourcePath }} --wait ${{ env.deployWait }}
