name: deltaDeploy

on:
  push:
    branches: [ "main" ]
    #paths:
    #  -  'force-app/**'  
  workflow_dispatch:
env:
  #personalToken: 
  GH_TOKEN: ${{ secrets.githubCLI }}
  latestCommitId: ${{ github.sha }}

jobs:
  deltaDeploy:
    runs-on: windows-latest
    environment: prod
    env:
      fromCommitId: ${{ vars.fromCommitId }}
    
    steps:
      - name: checkoutSourceCode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setupGIT
        run: |
          git config --global --add safe.directory /__w/Actions/Actions
          git config --global user.email "GitHub@mass.gov"
          git config --global user.name "GitHub User"
      
      - name: getChanges
        shell: pwsh
        run: |
          ./build/customScripts/deltaDeploy.ps1
      
      - name: exportSecret
        run: |
          echo "${{ secrets.secureKey }}" > server.key

      - name: extractSFCLI
        run: |
          tar -xzvf build/sf-win32-x64.tar.gz

      - name: sfJWTAuth
        run: |
          ./sf/bin/sf org login jwt --username ${{ vars.userName }} --jwt-key-file=server.key --client-id ${{ vars.consumerKey }} --instance-url ${{ vars.instanceURL }} --alias ${{ vars.orgAlias }}

      - name: deltaDeploy
        run: |
          ./sf/bin/sf project deploy start -o ${{ vars.orgAlias }} -l ${{ vars.testLevel }} --source-dir ${{ vars.sourcePath }} -w ${{ vars.deployWait }}

      - name: updateVariable
        shell: pwsh
        run: |
          gh variable set --env fromCommitId=${{ env:latestCommitId }}
#$latestCommit = $env:latestCommitId
#./build/customScripts/updateVariable.ps1 -commitId $latestCommit
          