name: fullDeploy

on:
  push:
    branches: [ "develop" ]
    paths:
      -  'force-app/**' 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment'
        type: choice
        required: true
        default: uat
        options:
          - uat
          - prod

jobs:
  fullDeploy:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      userName: ${{ vars.userName }}
      consumerKey: ${{ vars.consumerKey }}
      instanceURL: ${{ vars.instanceURL }}
      orgAlias: ${{ vars.orgAlias }}
      testLevel: ${{ vars.testLevel }}
      sourcePath: ${{ vars.sourcePath }}
      deployWait: ${{ vars.deployWait }}
      secureKey: ${{ secrets.secureKey }}

    steps:
      - name: checkoutSourceCode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configureGIT
        run: |
          git config --global --add safe.directory /__w/Actions/Actions
          git config --global user.email "GitHub@mass.gov"
          git config --global user.name "GitHub User"

      - name: extractSFCLI
        run: |
          tar -xzvf build/sf-win32-x64.tar.gz
      
      - name: installSFCLI
        run: |
          npm install sfdx-cli@latest-rc --global
          sf --version
      
      - name: sfJWTAuth
        run: |
          echo "$env:secureKey" > secure.key
          ./sf/bin/sf org login jwt --username ${{ env.userName }} --jwt-key-file=secure.key --client-id ${{ env.consumerKey }} --instance-url ${{ env.instanceURL }} --alias ${{ env.orgAlias }}

      - name: sfDeploy
        shell: pwsh
        run: |
          ./sf/bin/sf project deploy start -o ${{ env.orgAlias }} -l ${{ env.testLevel }} --source-dir ${{ env.sourcePath }} -w ${{ env.deployWait }}