name: fullDeploy

on:
  push:
    branches: [ "main" ]
    paths:
      -  'force-app/**'  
  workflow_dispatch:

jobs:
  fullDeploy:
    runs-on: windows-latest
    environment: prod
    env:
      userName: ${{ vars.userName }}
      clientId: ${{ vars.consumerKey }}
      instanceURL: ${{ vars.instanceURL }}
      orgAlias: ${{ vars.orgAlias }}
      testLevel: ${{ vars.testLevel }}
      sourcePath: ${{ vars.sourcePath }}
      deployWait: ${{ vars.deployWait }}
      secureKey: ${{ secrets.secureKey }}

    steps:
      - name: checkoutSourceCode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setupGIT
        run: |
          git config --global --add safe.directory /__w/Actions/Actions
          git config --global user.email "GitHub@mass.gov"
          git config --global user.name "GitHub User"
      
      - name: exportSecret
        run: |
          $stringtoEncode = $env:secureKey
          $base64Encoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($stringtoEncode))
          powershell -command "try { [Convert]::FromBase64String('%base64Encoded%') > $null; 'The string is base64 encoded.' } catch { 'The string is not base64 encoded.' }"
          echo $base64Encoded > data.b64 && certutil -decode data.b64 server.key

      - name: extractSFCLI
        run: |
          tar -xzvf build/sf-win32-x64.tar.gz

      - name: sfJWTAuth
        run: |
          ./sf/bin/sf org login jwt --username $userName --jwt-key-file=server.key --client-id $clientId --instance-url $instanceURL --alias $orgAlias

      - name: deltaDeploy
        shell: pwsh
        run: |
          ./sf/bin/sf project deploy start -o $orgAlias -l $testLevel --source-dir $sourcePath -w $deployWait