name: fullDeploy

on:
  push:
    branches: [ "main" ]
    paths:
      -  'force-app/**'  
  workflow_dispatch:

jobs:
  branch-deployment:
    runs-on: ubuntu-latest
    environment: prod
    container:
      image: salesforce/cli:latest-slim
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'save secret to file'
        run: | 
          echo "${{ secrets.secureKey }}" > server.key

      - name: 'sfdx auth'
        run: |
          sfdx force:auth:jwt:grant --username ${{ env.userName }} --jwt-key-file=server.key --client-id ${{ env.consumerKey }} --instance-url ${{ env.instanceURL }} --alias ${{ env.orgAlias }}

      - name: 'branch deploy'
        run: |
          sfdx force:source:deploy --targetusername ${{ env.orgAlias }} --testlevel ${{ env.testLevel }} --sourcepath ${{ vars.sourcePath }} --wait ${{ vars.deployWait }}
