name: incrementalDeploy

on:
  push:
    branches: [ "main" ]
    #paths:
    #  -  'force-app/**'  
  workflow_dispatch:
env:
  personalToken: ${{ secrets.personalToken }}

jobs:
  branch-deployment:
    runs-on: windows-latest
    container:
      image: salesforce/cli:latest-slim
    environment: prod
    env:
      fromCommitId: ${{ vars.fromCommitId }}
    
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'incremental deploy'
        shell: pwsh
        run: |
          ./build/customScripts/incrementalDeploy.ps1

      - name: 'update variable'
        run: |
          ./build/customScripts/updateVariable.ps1