name: incrementalDeploy

on:
  push:
    branches: [ "main" ]
    #paths:
    #  -  'force-app/**'  
  workflow_dispatch:
env:
  personalToken: ${{ secrets.personalToken }}

jobs:
  incrementalDeploy:
    runs-on: windows-latest
    environment: prod
    env:
      fromCommitId: ${{ vars.fromCommitId }}
    
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'getChanges'
        shell: pwsh
        run: |
          ./build/customScripts/incrementalDeploy.ps1
      
      - name: 'check Docker Image'
        run: |
          docker run --rm -v ${PWD}:/workspace -w /workspace salesforce/cli:latest-slim 
          echo "Salesforce CLI container is ready"
      
      - name: 'exportSecret'
        run: |
          echo "${{ secrets.secureKey }}" > server.key

      - name: 'sfAuth'
        run: |
          docker run --rm -v ${PWD}:/workspace -w /workspace salesforce/cli:latest-slim sfdx force:auth:jwt:grant --username ${{ vars.userName }} --jwt-key-file=server.key --client-id ${{ vars.consumerKey }} --instance-url ${{ vars.instanceURL }} --alias ${{ vars.orgAlias }}

      - name: 'incrementalDeploy'
        run: |
          docker run --rm -v ${PWD}:/workspace -w /workspace salesforce/cli:latest-slim sfdx force:source:deploy --loglevel ${{ vars.logLevel }} --targetusername ${{ vars.orgAlias }} --testlevel ${{ vars.testLevel }} --sourcepath ${{ vars.sourcePath }} --wait ${{ vars.deployWait }}

      - name: 'updateVariable'
        run: |
          ./build/customScripts/updateVariable.ps1