name: getPostCommitId

on:
  push:
    branches: [ "main" ]
    #paths:
    #  -  'force-app/**'  
  workflow_dispatch:

jobs:
  branch-deployment:
    runs-on: ubuntu-latest
    env:
      prod
    
    steps:
      - name: 'checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'get commit id'
        run: | 
          echo $fromCommitId