#Using Ubantu runner image & npm install for SF CLI

name: npmDeploy

on:
  push:
    branches: [ "dev"]
    paths:
      -  'force-app/**' 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment'
        type: choice
        required: true
        default: uat
        options:
          - uat
          - prod

jobs:
  fullDeploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      userName: ${{ vars.userName }}
      instanceURL: ${{ vars.instanceURL }}
      orgAlias: ${{ vars.orgAlias }}
      testLevel: ${{ vars.testLevel }}
      sourcePath: ${{ vars.sourcePath }}
      deployWait: ${{ vars.deployWait }}
      secureKey: ${{ secrets.secureKey }}
      consumerKey: ${{ secrets.consumerKey }}

    steps:
      - name: checkoutSourceCode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configureGIT
        run: |
          git config --global user.email "GitHub@mass.gov"
          git config --global user.name "GitHub User"

      - name: installSFCLI
        run: |
          npm install @salesforce/cli --global
          sf --version
      
      - name: sfJWTAuth
        run: |
          echo "${{ secrets.secureKey }}" > secure.key
          sf org login jwt --username ${{ env.userName }} --jwt-key-file=secure.key --client-id ${{ env.consumerKey }} --instance-url ${{ env.instanceURL }} --alias ${{ env.orgAlias }}

      - name: sfDeploy
        run: |
          sf project deploy start -o ${{ env.orgAlias }} -l ${{ env.testLevel }} --source-dir ${{ env.sourcePath }} -w ${{ env.deployWait }}