#Using Ubantu runner image & npm install for SF CLI

name: npmDeploy

on:
  push:
    branches:
      - dev
    paths:
      -  'force-app/**' 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy Environment'
        type: string
        required: true
        default: 'qa'
        options:
          - 'qa'
          - 'uat'
          - 'prod'

jobs:
  fullDeploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - name: checkoutSourceCode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: configureGIT
        run: |
          git config --global user.email "GitHub@mass.gov"
          git config --global user.name "GitHub User"

      - name: installSFCLI
        run: |
          npm install @salesforce/cli --global
          sf --version
      
      - name: sfJWTAuth
        run: |
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            ENVIRONMENT=${{ github.event.inputs.environment }}
          else
            ENVIRONMENT='qa'
          fi
          echo "Deploying to $ENVIRONMENT environment"
          echo "${{ secrets.secureKey }}" > secure.key
          sf org login jwt --username ${{ env.userName }} --jwt-key-file=secure.key --client-id ${{ env.consumerKey }} --instance-url ${{ env.instanceURL }} --alias ${{ env.orgAlias }}

      - name: sfDeploy
        run: |
          sf project deploy start -o ${{ env.orgAlias }} -l ${{ env.testLevel }} --source-dir ${{ env.sourcePath }} -w ${{ env.deployWait }}